# Generated by Django 5.2.13 on 2026-04-14 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0007_alter_liquid_born_alter_liquid_death'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfp',
            name='Dash',
        ),
        migrations.AddField(
            model_name='mfp',
            name='BF_DIC_Exposure_ms',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BF/DIC exp (ms)'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='DIC_BF_Imaging',
            field=models.BooleanField(blank=True, null=True, verbose_name='DIC/BF imaging?'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='DNA_Species_Concentration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DNA species and concentration'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Dialysis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dialysis?'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Dialysis_Duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dialysis duration'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='GFP_FITC_Exposure_ms',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GFP/FITC exp (ms)'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='IA_Composition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IA composition'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='IA_Osmolarity',
            field=models.IntegerField(blank=True, null=True, verbose_name='IA osmolarity'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Marker_Used',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marker used'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Membrane_Seal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Membrane seal'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='OA_Composition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OA composition'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='OA_Osmolarity',
            field=models.IntegerField(blank=True, null=True, verbose_name='OA osmolarity'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Objective',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Objective'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Oil_Seal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Oil seal'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Positions_Volume_Increase',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Positions with volume increase'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Post_Dialysis_IA_Osmolarity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Post-dialysis IA osmolarity'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Post_Dialysis_OA_Osmolarity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Post-dialysis OA osmolarity'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Production_Video_Usable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Production video usable?'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Experiment short name / purpose'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='mCherry_Exposure_ms',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mCherry exp (ms)'),
        ),
        migrations.AlterField(
            model_name='expbase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exppath',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exptype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fileending',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 14, 16, 42, 20, 113706), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 14, 16, 42, 20, 113713), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='observationhierarchy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
