# Generated by Django 5.2.13 on 2026-04-15 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0008_remove_mfp_dash_mfp_bf_dic_exposure_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfp',
            name='Frames_AI_Training',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Frames used for future AI training'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 15, 10, 47, 12, 170555), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 15, 10, 47, 12, 170561), null=True),
        ),
    ]
