# Generated by Django 5.2.13 on 2026-07-10 14:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0009_mfp_frames_ai_training_alter_liquid_born_and_more'),
        ('Lab_Dash', '0010_alter_sel_start_datetime_elli'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfp',
            name='Dash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_experiment', to='Lab_Dash.mfp'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 7, 10, 16, 47, 46, 310634), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 7, 10, 16, 47, 46, 310653), null=True),
        ),
    ]
