# Generated by Django 5.2.13 on 2026-07-10 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0010_mfp_dash_alter_liquid_born_alter_liquid_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 7, 10, 17, 51, 42, 877054), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 7, 10, 17, 51, 42, 877075), null=True),
        ),
    ]
