# Generated by Django 3.1.3 on 2021-05-17 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Misc', '0007_auto_20210517_1446'),
        ('Exp_Main', '0010_auto_20210517_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsd',
            name='Script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab_Misc.oszscriptgen'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 17, 19, 44, 20, 561351), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 17, 19, 44, 20, 561351), null=True),
        ),
    ]
