# Generated by Django 3.1.3 on 2021-05-29 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0013_auto_20210529_1225'),
        ('Exp_Main', '0012_auto_20210529_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 29, 12, 24, 56, 216664), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 29, 12, 24, 56, 216664), null=True),
        ),
        migrations.AlterField(
            model_name='rsd',
            name='Dash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab_Dash.rsd'),
        ),
    ]
