# Generated by Django 3.1.3 on 2021-05-29 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0013_auto_20210529_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kur',
            name='Dash',
        ),
        migrations.RemoveField(
            model_name='lpt',
            name='Dash',
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 29, 12, 29, 9, 7025), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 29, 12, 29, 9, 7025), null=True),
        ),
    ]
