# Generated by Django 3.1.3 on 2022-06-12 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0016_auto_20220612_1610'),
        ('Exp_Sub', '0016_auto_20220612_1610'),
        ('Exp_Main', '0015_auto_20220318_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 12, 16, 10, 19, 822582), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 12, 16, 10, 19, 822590), null=True),
        ),
        migrations.CreateModel(
            name='LMP',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Main.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
                ('Link_Data', models.TextField(blank=True, null=True)),
                ('Link_PDF', models.TextField(blank=True, null=True)),
                ('Link_Osz_join_LSP', models.TextField(blank=True, null=True)),
                ('Dash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab_Dash.lmp')),
                ('Sub_Exp', models.ManyToManyField(blank=True, to='Exp_Sub.ExpBase')),
            ],
            bases=('Exp_Main.expbase',),
        ),
    ]
