# Generated by Django 3.1.3 on 2022-11-02 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Sub', '0029_auto_20221102_1154'),
        ('Lab_Dash', '0029_auto_20221102_1154'),
        ('Exp_Main', '0028_auto_20221029_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 11, 54, 45, 111387), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 11, 54, 45, 111396), null=True),
        ),
        migrations.CreateModel(
            name='DAF',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Main.expbase')),
                ('Liquid', models.TextField(blank=True, null=True)),
                ('Drop_Volume_muL', models.FloatField(blank=True, null=True)),
                ('Rotations_per_min', models.FloatField(blank=True, null=True)),
                ('Trajectory_Radius_mm', models.FloatField(blank=True, null=True)),
                ('Velocity_mu_m_per_s', models.FloatField(blank=True, null=True)),
                ('Height_Glass_Plate_mm', models.FloatField(blank=True, null=True)),
                ('Capillary', models.IntegerField(blank=True, null=True)),
                ('Link', models.TextField(blank=True, null=True)),
                ('Link_Data', models.TextField(blank=True, null=True)),
                ('Link_Data_2nd_Camera', models.TextField(blank=True, null=True)),
                ('Link_Additional_Data_CAL', models.TextField(blank=True, null=True)),
                ('Link_Additional_Data_CAR', models.TextField(blank=True, null=True)),
                ('Link_Video', models.TextField(blank=True, null=True)),
                ('Link_Video_2nd_Camera', models.TextField(blank=True, null=True)),
                ('Link_Result', models.TextField(blank=True, null=True)),
                ('Dash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab_Dash.daf')),
                ('Sub_Exp', models.ManyToManyField(blank=True, to='Exp_Sub.ExpBase')),
            ],
            bases=('Exp_Main.expbase',),
        ),
    ]
