# Generated by Django 3.1.3 on 2023-02-26 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0031_auto_20221108_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmp',
            name='Distance_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmp',
            name='N_Monomers',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 26, 15, 57, 20, 647520), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 26, 15, 57, 20, 647520), null=True),
        ),
    ]
