# Generated by Django 3.1.3 on 2023-10-13 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0034_auto_20231013_1109'),
        ('Lab_Misc', '0014_auto_20221108_1427'),
        ('Exp_Sub', '0034_auto_20231013_1109'),
        ('Exp_Main', '0033_auto_20230306_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 13, 11, 9, 53, 76910), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 13, 11, 9, 53, 76910), null=True),
        ),
        migrations.CreateModel(
            name='GRV',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Main.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
                ('Link_Data', models.TextField(blank=True, null=True)),
                ('Link_PDF', models.TextField(blank=True, null=True)),
                ('Link_Osz_join_LSP', models.TextField(blank=True, null=True)),
                ('Temp_Observation', models.TextField(blank=True, null=True)),
                ('Temp_Hypothesis', models.TextField(blank=True, null=True)),
                ('Temp_Mixing_ratio', models.TextField(blank=True, null=True)),
                ('Temp_Atmosphere_relax', models.TextField(blank=True, null=True)),
                ('Temp_Flowrate', models.TextField(blank=True, null=True)),
                ('Temp_Volume', models.TextField(blank=True, null=True)),
                ('Temp_Buzz_word', models.TextField(blank=True, null=True)),
                ('Temp_Bath_time', models.TextField(blank=True, null=True)),
                ('Dash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab_Dash.grv')),
                ('Liquid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exp_Main.liquid')),
                ('Script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab_Misc.oszscriptgen')),
                ('Sub_Exp', models.ManyToManyField(blank=True, to='Exp_Sub.ExpBase')),
            ],
            bases=('Exp_Main.expbase',),
        ),
    ]
