# Generated by Django 3.1.3 on 2023-10-17 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0036_auto_20231013_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='grv',
            name='Dipping_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grv',
            name='Frame_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 15, 4, 27, 596486), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 15, 4, 27, 596486), null=True),
        ),
    ]
