# Generated by Django 3.1.3 on 2023-10-23 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0037_auto_20231017_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='grv',
            name='px_to_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 23, 19, 3, 23, 412776), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 23, 19, 3, 23, 412776), null=True),
        ),
    ]
