# Generated by Django 3.1.3 on 2023-11-01 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0046_auto_20231101_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='grv',
            name='Pix_Pos_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 1, 10, 54, 57, 543074), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 1, 10, 54, 57, 543074), null=True),
        ),
    ]
