# Generated by Django 3.1.3 on 2024-08-16 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0056_auto_20240219_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmp',
            name='w_cc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmp',
            name='w_cw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmp',
            name='w_pc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmp',
            name='w_pp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmp',
            name='w_pw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmp',
            name='w_ww',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 16, 14, 59, 15, 176721), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 16, 14, 59, 15, 176721), null=True),
        ),
    ]
