# Generated by Django 3.1.3 on 2024-08-16 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0057_auto_20240816_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmp',
            name='N_ETOH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmp',
            name='N_H2O',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 16, 16, 57, 38, 751414), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 16, 16, 57, 38, 751414), null=True),
        ),
    ]
