# Generated by Django 3.1.3 on 2024-08-16 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0059_auto_20240816_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 16, 23, 7, 29, 556807), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 16, 23, 7, 29, 556816), null=True),
        ),
    ]
