# Generated by Django 3.2.25 on 2026-01-20 14:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exp_Sub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GassesScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, db_column='Name:', null=True)),
                ('Periodicity', models.IntegerField(blank=True, default=3, null=True)),
                ('StartNumber', models.TextField(blank=True, default=0, null=True)),
                ('Name_of_gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exp_Sub.gas')),
            ],
        ),
        migrations.CreateModel(
            name='Polymer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(unique=True)),
                ('Material', models.TextField(blank=True, null=True)),
                ('Manufactured', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Manufacturer', models.TextField(blank=True, null=True)),
                ('Number_average_kDa', models.FloatField(blank=True, null=True)),
                ('Weight_average_kDa', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, db_column='Name:', null=True, unique=True)),
                ('Description', models.TextField(blank=True, db_column='Description:', null=True)),
                ('Conclusion', models.TextField(blank=True, db_column='Conclusion:', null=True)),
                ('Issued', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('DueDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 31, 0, 0))),
                ('Fineshed', models.BooleanField(verbose_name='Fineshed:')),
            ],
        ),
        migrations.CreateModel(
            name='SampleBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(unique=True)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Lab_Misc.samplebase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PseudoSample',
            fields=[
                ('samplebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lab_Misc.samplebase')),
            ],
            options={
                'abstract': False,
            },
            bases=('Lab_Misc.samplebase',),
        ),
        migrations.CreateModel(
            name='SampleBlank',
            fields=[
                ('samplebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lab_Misc.samplebase')),
                ('Material', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Length_cm', models.FloatField(blank=True, null=True)),
                ('Width_cm', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Lab_Misc.samplebase',),
        ),
        migrations.CreateModel(
            name='SampleGroovedPlate',
            fields=[
                ('samplebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lab_Misc.samplebase')),
                ('Material', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Nr_grooves', models.IntegerField(blank=True, null=True)),
                ('Nr_Ridges', models.IntegerField(blank=True, null=True)),
                ('Groove_depth_mm', models.FloatField(blank=True, null=True)),
                ('Groove_width_mm', models.FloatField(blank=True, null=True)),
                ('Ridge_width_mm', models.FloatField(blank=True, null=True)),
                ('Length_cm', models.FloatField(blank=True, null=True)),
                ('Width_cm', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Lab_Misc.samplebase',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, db_column='Name:', null=True, unique=True)),
                ('Description', models.TextField(blank=True, db_column='Description:', null=True)),
                ('Issued', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('DueDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 31, 0, 0))),
                ('Fineshed', models.BooleanField(verbose_name='Fineshed:')),
                ('Priory', models.CharField(choices=[('1', 'Critical'), ('2', 'High'), ('3', 'Medium'), ('4', 'Low')], default='3', max_length=1)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('Entry', models.ManyToManyField(blank=True, to='Lab_Misc.ProjectEntry')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Lab_Misc.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OszScriptGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, db_column='Name:', null=True)),
                ('init_drop', models.FloatField(blank=True, default=3, null=True)),
                ('factor', models.FloatField(blank=True, default=1.5, null=True)),
                ('delay', models.FloatField(blank=True, default=30, null=True)),
                ('number_of_cycles', models.IntegerField(blank=True, default=9, null=True)),
                ('base_flow', models.FloatField(blank=True, default=6, null=True)),
                ('diff_flow', models.FloatField(blank=True, default=1, null=True)),
                ('faktor_zeit', models.FloatField(blank=True, default=1000, null=True)),
                ('scaling_vol', models.FloatField(blank=True, default=1, null=True)),
                ('add_with_const', models.FloatField(blank=True, default=0.5, null=True)),
                ('add_with_fakt_zeit', models.FloatField(blank=True, default=120, null=True)),
                ('add_with_scal_vol', models.FloatField(blank=True, default=0.6666666666666666, null=True)),
                ('max_time', models.FloatField(blank=True, default=500, null=True)),
                ('max_time_pls_increase', models.FloatField(blank=True, default=0, null=True)),
                ('Temperatures', models.TextField(blank=True, null=True)),
                ('Link_folder_script', models.TextField(blank=True, null=True)),
                ('Link_pump_df', models.TextField(blank=True, null=True)),
                ('Link_gas_df', models.TextField(blank=True, null=True)),
                ('Link_temperatures_df', models.TextField(blank=True, null=True)),
                ('Gas', models.ManyToManyField(blank=True, to='Lab_Misc.GassesScript')),
            ],
        ),
        migrations.CreateModel(
            name='SamplePseudoBrushPDMSGlass',
            fields=[
                ('samplebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lab_Misc.samplebase')),
                ('Parent', models.TextField(blank=True, null=True)),
                ('Birth', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Death', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Length_cm', models.FloatField(blank=True, null=True)),
                ('Width_cm', models.FloatField(blank=True, null=True)),
                ('Thickness_PDMS_nm', models.FloatField(blank=True, null=True)),
                ('Polymer', models.ManyToManyField(blank=True, to='Lab_Misc.Polymer')),
            ],
            options={
                'abstract': False,
            },
            bases=('Lab_Misc.samplebase',),
        ),
        migrations.CreateModel(
            name='SampleHydrogelPNiPAAm',
            fields=[
                ('samplebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lab_Misc.samplebase')),
                ('Parent', models.TextField(blank=True, null=True)),
                ('Birth', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Death', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Length_cm', models.FloatField(blank=True, null=True)),
                ('Width_cm', models.FloatField(blank=True, null=True)),
                ('Thickness_PNiPAAm_nm', models.FloatField(blank=True, null=True)),
                ('Polymer', models.ManyToManyField(blank=True, to='Lab_Misc.Polymer')),
            ],
            options={
                'abstract': False,
            },
            bases=('Lab_Misc.samplebase',),
        ),
        migrations.CreateModel(
            name='SampleGelPDMS',
            fields=[
                ('samplebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lab_Misc.samplebase')),
                ('Parent', models.TextField(blank=True, null=True)),
                ('Stretching_degree', models.FloatField(blank=True, null=True)),
                ('Birth', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Death', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Length_cm', models.FloatField(blank=True, null=True)),
                ('Width_cm', models.FloatField(blank=True, null=True)),
                ('Thickness_PNiPAAm_mm', models.FloatField(blank=True, null=True)),
                ('Polymer', models.ManyToManyField(blank=True, to='Lab_Misc.Polymer')),
            ],
            options={
                'abstract': False,
            },
            bases=('Lab_Misc.samplebase',),
        ),
        migrations.CreateModel(
            name='SampleBrushPNiPAAmSi',
            fields=[
                ('samplebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lab_Misc.samplebase')),
                ('Parent', models.TextField(blank=True, null=True)),
                ('Birth', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Death', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Length_cm', models.FloatField(blank=True, null=True)),
                ('Width_cm', models.FloatField(blank=True, null=True)),
                ('Thickness_SiO2_nm', models.FloatField(blank=True, null=True)),
                ('Thickness_PGMA_nm', models.FloatField(blank=True, null=True)),
                ('Thickness_PNiPAAm_nm', models.FloatField(blank=True, null=True)),
                ('Number_on_back', models.IntegerField(blank=True, null=True)),
                ('Polymer', models.ManyToManyField(blank=True, to='Lab_Misc.Polymer')),
            ],
            options={
                'abstract': False,
            },
            bases=('Lab_Misc.samplebase',),
        ),
        migrations.CreateModel(
            name='SampleBrushPNiPAAmInfasil',
            fields=[
                ('samplebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lab_Misc.samplebase')),
                ('Parent', models.TextField(blank=True, null=True)),
                ('Birth', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Death', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Diameter_cm', models.FloatField(blank=True, null=True)),
                ('Thickness_PGMA_nm', models.FloatField(blank=True, null=True)),
                ('Thickness_PNiPAAm_nm', models.FloatField(blank=True, null=True)),
                ('Number_on_back', models.IntegerField(blank=True, null=True)),
                ('Polymer', models.ManyToManyField(blank=True, to='Lab_Misc.Polymer')),
            ],
            options={
                'abstract': False,
            },
            bases=('Lab_Misc.samplebase',),
        ),
        migrations.CreateModel(
            name='SampleBrushPNiPAAmGlass',
            fields=[
                ('samplebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lab_Misc.samplebase')),
                ('Parent', models.TextField(blank=True, null=True)),
                ('Birth', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Death', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Length_cm', models.FloatField(blank=True, null=True)),
                ('Width_cm', models.FloatField(blank=True, null=True)),
                ('Thickness_SiO2_nm', models.FloatField(blank=True, null=True)),
                ('Thickness_PGMA_nm', models.FloatField(blank=True, null=True)),
                ('Thickness_PNiPAAm_nm', models.FloatField(blank=True, null=True)),
                ('Number_on_back', models.IntegerField(blank=True, null=True)),
                ('Polymer', models.ManyToManyField(blank=True, to='Lab_Misc.Polymer')),
            ],
            options={
                'abstract': False,
            },
            bases=('Lab_Misc.samplebase',),
        ),
    ]
