# Generated by Django 3.1.3 on 2021-05-16 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Sub', '0006_auto_20210516_1744'),
        ('Lab_Misc', '0002_auto_20210506_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='OszScriptGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, db_column='Name:', null=True, unique=True)),
                ('Description', models.TextField(blank=True, db_column='Description:', null=True)),
                ('Conclusion', models.TextField(blank=True, db_column='Conclusion:', null=True)),
                ('Issued', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('DueDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 31, 0, 0))),
                ('Fineshed', models.BooleanField(verbose_name='Fineshed:')),
            ],
        ),
        migrations.CreateModel(
            name='Gasses_script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, db_column='Name:', null=True, unique=True)),
                ('Description', models.TextField(blank=True, db_column='Description:', null=True)),
                ('Conclusion', models.TextField(blank=True, db_column='Conclusion:', null=True)),
                ('Issued', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('DueDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 31, 0, 0))),
                ('Fineshed', models.BooleanField(verbose_name='Fineshed:')),
                ('Entry', models.ManyToManyField(blank=True, to='Exp_Sub.Gas')),
            ],
        ),
    ]
