# Generated by Django 3.1.3 on 2021-05-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Sub', '0007_auto_20210516_1746'),
        ('Lab_Misc', '0003_gasses_script_oszscriptgen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gasses_script',
            new_name='GassesScript',
        ),
    ]
