# Generated by Django 3.1.3 on 2021-05-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Sub', '0008_auto_20210516_1759'),
        ('Lab_Misc', '0004_auto_20210516_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gassesscript',
            name='Conclusion',
        ),
        migrations.RemoveField(
            model_name='gassesscript',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='gassesscript',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='gassesscript',
            name='Entry',
        ),
        migrations.RemoveField(
            model_name='gassesscript',
            name='Fineshed',
        ),
        migrations.RemoveField(
            model_name='gassesscript',
            name='Issued',
        ),
        migrations.RemoveField(
            model_name='oszscriptgen',
            name='Conclusion',
        ),
        migrations.RemoveField(
            model_name='oszscriptgen',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='oszscriptgen',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='oszscriptgen',
            name='Fineshed',
        ),
        migrations.RemoveField(
            model_name='oszscriptgen',
            name='Issued',
        ),
        migrations.AddField(
            model_name='gassesscript',
            name='Periodicity',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='gassesscript',
            name='StartNumber',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='Gas',
            field=models.ManyToManyField(blank=True, to='Lab_Misc.GassesScript'),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='Link_folder_script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='Link_gas_df',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='Link_pump_df',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='add_with_const',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='add_with_fakt_zeit',
            field=models.FloatField(blank=True, default=120, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='add_with_scal_vol',
            field=models.FloatField(blank=True, default=0.6666666666666666, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='base_flow',
            field=models.FloatField(blank=True, default=6, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='delay',
            field=models.FloatField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='diff_flow',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='factor',
            field=models.FloatField(blank=True, default=1.5, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='faktor_zeit',
            field=models.FloatField(blank=True, default=1000, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='init_drop',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='number_of_cycles',
            field=models.FloatField(blank=True, default=9, null=True),
        ),
        migrations.AddField(
            model_name='oszscriptgen',
            name='scaling_vol',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gassesscript',
            name='Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exp_Sub.gas'),
            preserve_default=False,
        ),
    ]
