# Generated by Django 3.1.3 on 2022-08-16 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Misc', '0008_auto_20220318_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleHydrogelPNiPAAm',
            fields=[
                ('samplebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lab_Misc.samplebase')),
                ('Parent', models.TextField(blank=True, null=True)),
                ('Birth', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Death', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Length_cm', models.FloatField(blank=True, null=True)),
                ('Width_cm', models.FloatField(blank=True, null=True)),
                ('Thickness_PNiPAAm_nm', models.FloatField(blank=True, null=True)),
                ('Polymer', models.ManyToManyField(blank=True, to='Lab_Misc.Polymer')),
            ],
            options={
                'abstract': False,
            },
            bases=('Lab_Misc.samplebase',),
        ),
    ]
