# Generated by Django 3.1.3 on 2022-08-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Misc', '0010_oszscriptgen_temperatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='oszscriptgen',
            name='Link_temperatures_df',
            field=models.TextField(blank=True, null=True),
        ),
    ]
