# Generated by Django 3.1.3 on 2023-10-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Misc', '0014_auto_20221108_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleGroovedPlate',
            fields=[
                ('samplebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lab_Misc.samplebase')),
                ('Material', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Length_cm', models.FloatField(blank=True, null=True)),
                ('Width_cm', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Lab_Misc.samplebase',),
        ),
    ]
