# Generated by Django 3.1.3 on 2023-11-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Misc', '0015_samplegroovedplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplegroovedplate',
            name='Groove_depth_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplegroovedplate',
            name='Groove_width_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplegroovedplate',
            name='Nr_grooves',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
