# Generated by Django 3.1.3 on 2023-11-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Misc', '0016_auto_20231101_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplegroovedplate',
            name='Ridge_width_mm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
