# Generated by Django 3.1.3 on 2023-11-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Misc', '0017_samplegroovedplate_ridge_width_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplegroovedplate',
            name='Nr_Ridges',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
