# Generated by Django 3.2.25 on 2026-01-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exp_Main', '0001_initial'),
        ('Lab_Dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrvAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True)),
                ('Exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exp_Main.expbase')),
            ],
        ),
        migrations.CreateModel(
            name='OszAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(unique=True)),
                ('Drop_center', models.FloatField(blank=True, null=True)),
                ('Hit_prec', models.FloatField(blank=True, null=True)),
                ('Exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exp_Main.expbase')),
            ],
        ),
        migrations.CreateModel(
            name='OszBaseParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drop_Nr', models.IntegerField(blank=True, null=True)),
                ('LoR_CL', models.TextField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right')], null=True)),
                ('Max_CL', models.FloatField(blank=True, null=True)),
                ('Max_CA', models.FloatField(blank=True, null=True)),
                ('Min_CA', models.FloatField(blank=True, null=True)),
                ('Min_AdvCA', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OszDerivedRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drop_Nr', models.IntegerField(blank=True, null=True)),
                ('LoR_CL', models.TextField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right')], null=True)),
                ('Hit_prec', models.FloatField(blank=True, null=True)),
                ('Fit_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OszFitRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drop_Nr', models.IntegerField(blank=True, null=True)),
                ('LoR_CL', models.TextField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right')], null=True)),
                ('ErroVal', models.TextField(blank=True, choices=[('Value', 'Value'), ('Error', 'Error')], null=True)),
                ('x_pos', models.FloatField(blank=True, null=True)),
                ('y_pos', models.FloatField(blank=True, null=True)),
                ('Step_width', models.FloatField(blank=True, null=True)),
                ('Step_hight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointsShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_pos', models.TextField(blank=True, choices=[('upper_on_hill', 'upper_on_hill'), ('upper_on_plate', 'upper_on_plate'), ('white_upper_on_hill', 'white_upper_on_hill'), ('white_upper_on_plate', 'white_upper_on_plate'), ('lower_in_groove', 'lower_in_groove'), ('upper_in_groove', 'upper_in_groove'), ('on_hill_edge', 'on_hill_edge'), ('white_lower_in_groove', 'white_lower_in_groove'), ('white_upper_in_groove', 'white_upper_in_groove')], null=True)),
                ('Position', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteadyShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frame', models.IntegerField(blank=True, null=True)),
                ('NrAvrgFrame', models.IntegerField(blank=True, default=3, null=True)),
                ('Type_state', models.TextField(blank=True, choices=[('steady', 'steady'), ('static', 'static')], null=True)),
                ('PointsShift', models.ManyToManyField(blank=True, to='Analysis.PointsShift')),
            ],
        ),
        migrations.CreateModel(
            name='OszAnalysisJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True, unique=True)),
                ('Dash', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Lab_Dash.oszanalysis')),
                ('OszAnalysis', models.ManyToManyField(blank=True, to='Analysis.OszAnalysis')),
            ],
        ),
        migrations.AddField(
            model_name='oszanalysis',
            name='OszBaseParam',
            field=models.ManyToManyField(blank=True, to='Analysis.OszBaseParam'),
        ),
        migrations.AddField(
            model_name='oszanalysis',
            name='OszDerivedRes',
            field=models.ManyToManyField(blank=True, to='Analysis.OszDerivedRes'),
        ),
        migrations.AddField(
            model_name='oszanalysis',
            name='OszFitRes',
            field=models.ManyToManyField(blank=True, to='Analysis.OszFitRes'),
        ),
        migrations.CreateModel(
            name='MFPAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particle_Diameter', models.IntegerField(default=11)),
                ('Threshold', models.FloatField(default=10.0)),
                ('Detect_Channel', models.IntegerField(default=0)),
                ('Result_Path', models.TextField(blank=True, null=True)),
                ('Entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Analysis', to='Lab_Dash.mfp')),
            ],
        ),
        migrations.CreateModel(
            name='LMPCosolventAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(unique=True)),
                ('Anz_H2O', models.FloatField(blank=True, null=True)),
                ('Anz_EtOH', models.FloatField(blank=True, null=True)),
                ('Height', models.FloatField(blank=True, null=True)),
                ('Height_Err', models.FloatField(blank=True, null=True)),
                ('Link_Hist_Mono', models.TextField(blank=True, null=True)),
                ('Link_Hist_H2O', models.TextField(blank=True, null=True)),
                ('Link_Hist_EtOH', models.TextField(blank=True, null=True)),
                ('Exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exp_Main.expbase')),
            ],
        ),
        migrations.CreateModel(
            name='GrvAnalysisJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True, unique=True)),
                ('Dash', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Lab_Dash.grvanalysis')),
                ('GrvAnalysis', models.ManyToManyField(blank=True, to='Analysis.GrvAnalysis')),
            ],
        ),
        migrations.AddField(
            model_name='grvanalysis',
            name='SteadyShift',
            field=models.ManyToManyField(blank=True, to='Analysis.SteadyShift'),
        ),
        migrations.CreateModel(
            name='DafAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True, unique=True)),
                ('Experiments', models.ManyToManyField(blank=True, to='Exp_Main.DAF')),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True, unique=True)),
                ('Dash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab_Dash.comparison')),
                ('ExpBase', models.ManyToManyField(blank=True, to='Exp_Main.ExpBase')),
            ],
        ),
    ]
