# Generated by Django 3.1.3 on 2022-06-14 16:10

import Analysis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0018_auto_20220614_1810'),
        ('Analysis', '0001_squashed_0004_auto_20210311_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMPCosolventAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(unique=True)),
                ('Anz_H2O', models.FloatField(blank=True, verbose_name=Analysis.models.OszBaseParam)),
                ('Anz_EtOH', models.FloatField(blank=True, verbose_name=Analysis.models.OszFitRes)),
                ('Height', models.FloatField(blank=True, verbose_name=Analysis.models.OszDerivedRes)),
                ('Link_Hist_Mono', models.TextField(blank=True, null=True)),
                ('Link_Hist_H2O', models.TextField(blank=True, null=True)),
                ('Link_Hist_EtOH', models.TextField(blank=True, null=True)),
                ('Exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exp_Main.expbase')),
            ],
        ),
    ]
