# Generated by Django 3.2.25 on 2026-01-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfpanalysis',
            name='Min_Dist',
            field=models.FloatField(default=70.0, verbose_name='Min Distance (px)'),
        ),
    ]
