# Generated by Django 3.2.25 on 2026-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0002_mfpanalysis_min_dist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfpanalysis',
            name='Noise_Size',
            field=models.FloatField(default=3.0, verbose_name='Noise Size (px)'),
        ),
    ]
