# Generated by Django 3.2.25 on 2026-04-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0003_mfpanalysis_noise_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfpanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mfpanalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Last Error Message'),
        ),
        migrations.AddField(
            model_name='mfpanalysis',
            name='execution_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Execution Time (s)'),
        ),
        migrations.AddField(
            model_name='mfpanalysis',
            name='is_plausible',
            field=models.BooleanField(default=True, verbose_name='Result is Plausible'),
        ),
        migrations.AddField(
            model_name='mfpanalysis',
            name='stable_tracks',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stable Tracks'),
        ),
        migrations.AddField(
            model_name='mfpanalysis',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('completed', 'Completed')], default='not_started', max_length=20, verbose_name='Analysis Status'),
        ),
        migrations.AddField(
            model_name='mfpanalysis',
            name='total_particles',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Particles Found'),
        ),
        migrations.AddField(
            model_name='mfpanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mfpanalysis',
            name='warning_message',
            field=models.TextField(blank=True, null=True, verbose_name='Warnings / Implausibility Reasons'),
        ),
        migrations.AlterField(
            model_name='mfpanalysis',
            name='Detect_Channel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mfpanalysis',
            name='Particle_Diameter',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='mfpanalysis',
            name='Threshold',
            field=models.FloatField(default=100.0),
        ),
    ]
