# Generated by Django 3.1.3 on 2022-11-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0029_auto_20221102_1154'),
        ('Analysis', '0003_auto_20220614_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='DafAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True, unique=True)),
                ('Experiments', models.ManyToManyField(blank=True, to='Exp_Main.DAF')),
            ],
        ),
    ]
