# Generated by Django 3.1.3 on 2023-11-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Main', '0042_auto_20231031_2351'),
        ('Analysis', '0004_dafanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_pos', models.TextField(blank=True, choices=[('lower_on_hill', 'lower_on_hill'), ('lower_in_groove', 'lower_in_groove'), ('upper_in_groove', 'upper_in_groove'), ('white_lower_in_groove', 'white_lower_in_groove'), ('white_upper_in_groove', 'white_upper_in_groove')], null=True)),
                ('Position', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteadyShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frame', models.IntegerField(blank=True, null=True)),
                ('NrAvrgFrame', models.IntegerField(blank=True, null=True)),
                ('Type_state', models.TextField(blank=True, choices=[('steady', 'steady'), ('static', 'static')], null=True)),
                ('PointsShift', models.ManyToManyField(blank=True, to='Analysis.PointsShift')),
            ],
        ),
        migrations.CreateModel(
            name='GrvAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(unique=True)),
                ('Exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exp_Main.expbase')),
                ('SteadyShift', models.ManyToManyField(blank=True, to='Analysis.SteadyShift')),
            ],
        ),
    ]
