# Generated by Django 3.2.25 on 2026-04-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0004_auto_20260413_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfpanalysis',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('failed', 'Failed'), ('implausible', 'Is Implausible'), ('needs_review', 'Needs Review'), ('completed', 'Completed')], default='not_started', max_length=20, verbose_name='Analysis Status'),
        ),
    ]
