# Generated by Django 5.2.13 on 2026-07-10 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0006_alter_comparison_id_alter_dafanalysis_id_and_more'),
        ('Exp_Main', '0010_mfp_dash_alter_liquid_born_alter_liquid_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfpanalysis',
            name='Entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Analysis', to='Exp_Main.mfp'),
        ),
    ]
