# Generated by Django 3.1.3 on 2023-11-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0007_auto_20231101_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grvanalysis',
            name='Name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
