# Generated by Django 3.1.3 on 2023-11-08 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0049_auto_20231107_2039'),
        ('Analysis', '0008_auto_20231101_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsshift',
            name='Type_pos',
            field=models.TextField(blank=True, choices=[('upper_on_hill', 'upper_on_hill'), ('lower_in_groove', 'lower_in_groove'), ('upper_in_groove', 'upper_in_groove'), ('white_lower_in_groove', 'white_lower_in_groove'), ('white_upper_in_groove', 'white_upper_in_groove')], null=True),
        ),
        migrations.CreateModel(
            name='GrvAnalysisJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True, unique=True)),
                ('Dash', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Lab_Dash.grvanalysis')),
                ('GrvAnalysis', models.ManyToManyField(blank=True, to='Analysis.GrvAnalysis')),
            ],
        ),
    ]
