# Generated by Django 3.1.3 on 2024-08-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0012_auto_20240213_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmpcosolventanalysis',
            name='Height_Err',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
