# Generated by Django 3.1.3 on 2021-05-06 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0001_squashed_0062_auto_20210427_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 6, 12, 1, 17, 962773), null=True),
        ),
    ]
