# Generated by Django 3.2.25 on 2026-01-29 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 29, 13, 6, 26, 721736), null=True),
        ),
    ]
