# Generated by Django 3.2.25 on 2026-01-29 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0002_alter_sel_start_datetime_elli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 29, 13, 40, 22, 364054), null=True),
        ),
    ]
