# Generated by Django 3.1.3 on 2021-05-06 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0003_auto_20210506_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grp',
            name='Name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 6, 22, 43, 5, 828767), null=True),
        ),
    ]
