# Generated by Django 3.2.25 on 2026-04-13 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0003_alter_sel_start_datetime_elli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 13, 11, 12, 19, 428102), null=True),
        ),
    ]
