# Generated by Django 3.2.25 on 2026-04-13 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0004_alter_sel_start_datetime_elli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 13, 13, 33, 27, 893368), null=True),
        ),
    ]
