# Generated by Django 3.1.3 on 2021-05-16 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0004_auto_20210506_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 16, 15, 27, 22, 751674), null=True),
        ),
    ]
