# Generated by Django 5.2.13 on 2026-04-13 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0005_alter_sel_start_datetime_elli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 13, 16, 26, 31, 682074), null=True),
        ),
    ]
