# Generated by Django 5.2.13 on 2026-04-15 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0008_alter_comparison_id_alter_comparisonentry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 15, 10, 47, 12, 162309), null=True),
        ),
    ]
