# Generated by Django 3.1.3 on 2021-05-17 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0009_auto_20210516_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 17, 14, 46, 26, 346644), null=True),
        ),
    ]
