# Generated by Django 5.2.13 on 2026-07-10 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0009_alter_sel_start_datetime_elli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 7, 10, 16, 47, 46, 292779), null=True),
        ),
    ]
