# Generated by Django 5.2.13 on 2026-07-10 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0010_alter_sel_start_datetime_elli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfp',
            name='BD_high_mm',
        ),
        migrations.RemoveField(
            model_name='mfp',
            name='BD_low_mm',
        ),
        migrations.RemoveField(
            model_name='mfp',
            name='CA_high_degree',
        ),
        migrations.RemoveField(
            model_name='mfp',
            name='CA_low_degree',
        ),
        migrations.RemoveField(
            model_name='mfp',
            name='Residual',
        ),
        migrations.RemoveField(
            model_name='mfp',
            name='Time_diff_pump',
        ),
        migrations.RemoveField(
            model_name='mfp',
            name='Time_diff_vid',
        ),
        migrations.RemoveField(
            model_name='mfp',
            name='Time_high_sec',
        ),
        migrations.RemoveField(
            model_name='mfp',
            name='Time_low_sec',
        ),
        migrations.AddField(
            model_name='mfp',
            name='Connected_IDs',
            field=models.TextField(blank=True, help_text="Defines tracked particles that are actually the same. Suggested format: '1:2, 4:5' (Particle 1 is merged into 2).", null=True, verbose_name='Connected IDs'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Excluded_IDs',
            field=models.CharField(blank=True, help_text="Comma-separated list of particle IDs to ignore (e.g., '4, 12, 15').", max_length=500, null=True, verbose_name='IDs to Exclude'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='Radius_Cutoff',
            field=models.FloatField(default=40.0, help_text='Particles with a radius larger than this value will be ignored.', verbose_name='Radius Cut-off (px)'),
        ),
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 7, 10, 17, 51, 42, 859202), null=True),
        ),
    ]
