# Generated by Django 3.1.3 on 2021-05-29 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0011_auto_20210517_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True, unique=True)),
                ('CA_high_degree', models.FloatField(blank=True, null=True)),
                ('CA_low_degree', models.FloatField(blank=True, null=True)),
                ('BD_high_mm', models.FloatField(blank=True, null=True)),
                ('BD_low_mm', models.FloatField(blank=True, null=True)),
                ('Time_high_sec', models.FloatField(blank=True, null=True)),
                ('Time_low_sec', models.FloatField(blank=True, null=True)),
                ('Time_diff_pump', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 29, 12, 23, 0, 475395), null=True),
        ),
    ]
