# Generated by Django 3.1.3 on 2022-03-18 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0014_auto_20210529_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 18, 13, 20, 51, 808994), null=True),
        ),
    ]
