# Generated by Django 3.1.3 on 2022-06-13 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0016_auto_20220612_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 13, 16, 19, 22, 609623), null=True),
        ),
    ]
