# Generated by Django 3.1.3 on 2022-06-14 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0017_auto_20220613_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 18, 10, 52, 242481), null=True),
        ),
    ]
