# Generated by Django 3.1.3 on 2022-08-10 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0020_auto_20220614_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 10, 13, 26, 22, 747164), null=True),
        ),
    ]
