# Generated by Django 3.1.3 on 2022-08-16 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0021_auto_20220810_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 16, 15, 56, 19, 874107), null=True),
        ),
    ]
