# Generated by Django 3.1.3 on 2022-08-21 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0022_auto_20220816_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 21, 14, 28, 59, 339906), null=True),
        ),
    ]
