# Generated by Django 3.1.3 on 2022-08-22 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0024_auto_20220822_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 22, 21, 34, 23, 684975), null=True),
        ),
    ]
