# Generated by Django 3.1.3 on 2022-10-03 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0025_auto_20220822_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsd',
            name='Residual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 3, 21, 5, 13, 460691), null=True),
        ),
    ]
