# Generated by Django 3.1.3 on 2022-10-18 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0026_auto_20221003_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 18, 22, 37, 18, 363438), null=True),
        ),
    ]
