# Generated by Django 3.1.3 on 2022-10-29 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0027_auto_20221018_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsd',
            name='Time_diff_vid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 29, 14, 21, 3, 950560), null=True),
        ),
    ]
