# Generated by Django 3.1.3 on 2022-11-02 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0028_auto_20221029_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True, unique=True)),
                ('CA_high_degree', models.FloatField(blank=True, null=True)),
                ('CA_low_degree', models.FloatField(blank=True, null=True)),
                ('BD_high_mm', models.FloatField(blank=True, null=True)),
                ('BD_low_mm', models.FloatField(blank=True, null=True)),
                ('Width_high_mm', models.FloatField(blank=True, null=True)),
                ('Width_low_mm', models.FloatField(blank=True, null=True)),
                ('Force_high_muN', models.FloatField(blank=True, null=True)),
                ('Force_low_muN', models.FloatField(blank=True, null=True)),
                ('Time_high_sec', models.FloatField(blank=True, null=True)),
                ('Time_low_sec', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DafAnalysisEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True)),
                ('Label', models.TextField(blank=True, null=True)),
                ('DafAnalysisID', models.IntegerField(blank=True, null=True)),
                ('X_high', models.FloatField(blank=True, null=True)),
                ('X_low', models.FloatField(blank=True, null=True)),
                ('Y_high', models.FloatField(blank=True, null=True)),
                ('Y_low', models.FloatField(blank=True, null=True)),
                ('X_shift', models.FloatField(blank=True, null=True)),
                ('Y_shift', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 11, 54, 45, 45248), null=True),
        ),
        migrations.CreateModel(
            name='DafAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True)),
                ('Title', models.TextField(blank=True, null=True)),
                ('X_shift', models.FloatField(blank=True, null=True)),
                ('Y_shift', models.FloatField(blank=True, null=True)),
                ('X_high', models.FloatField(blank=True, null=True)),
                ('X_low', models.FloatField(blank=True, null=True)),
                ('Y_high', models.FloatField(blank=True, null=True)),
                ('Y_low', models.FloatField(blank=True, null=True)),
                ('Entry', models.ManyToManyField(blank=True, to='Lab_Dash.DafAnalysisEntry')),
            ],
        ),
    ]
