# Generated by Django 3.1.3 on 2023-02-26 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0031_auto_20221108_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 26, 15, 57, 20, 632517), null=True),
        ),
    ]
