# Generated by Django 3.1.3 on 2023-03-06 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0032_auto_20230226_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='sel',
            name='Krit_mse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sel',
            name='Mse_time_delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sel',
            name='Temp_pelt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 6, 21, 3, 19, 266868), null=True),
        ),
    ]
