# Generated by Django 3.1.3 on 2023-10-13 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0035_auto_20231013_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 13, 11, 35, 38, 555685), null=True),
        ),
    ]
