# Generated by Django 3.1.3 on 2023-10-17 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0036_auto_20231013_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 15, 4, 27, 556881), null=True),
        ),
    ]
