# Generated by Django 3.1.3 on 2023-10-23 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0037_auto_20231017_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 23, 19, 3, 23, 384737), null=True),
        ),
    ]
