# Generated by Django 3.1.3 on 2023-10-30 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0038_auto_20231023_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 30, 11, 42, 14, 150812), null=True),
        ),
    ]
