# Generated by Django 3.1.3 on 2023-11-01 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0042_auto_20231031_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 31, 23, 55, 20, 926535), null=True),
        ),
    ]
