# Generated by Django 3.1.3 on 2023-11-01 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0046_auto_20231101_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 1, 10, 54, 57, 508983), null=True),
        ),
    ]
