# Generated by Django 3.1.3 on 2023-11-08 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0048_auto_20231101_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 7, 20, 39, 39, 240029), null=True),
        ),
        migrations.CreateModel(
            name='GrvAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True)),
                ('Title', models.TextField(blank=True, null=True)),
                ('X_shift', models.FloatField(blank=True, null=True)),
                ('Y_shift', models.FloatField(blank=True, null=True)),
                ('X_high', models.FloatField(blank=True, null=True)),
                ('X_low', models.FloatField(blank=True, null=True)),
                ('Y_high', models.FloatField(blank=True, null=True)),
                ('Y_low', models.FloatField(blank=True, null=True)),
                ('Entry', models.ManyToManyField(blank=True, to='Lab_Dash.OszAnalysisEntry')),
            ],
        ),
    ]
