# Generated by Django 3.1.3 on 2023-11-21 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0049_auto_20231107_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 21, 15, 15, 21, 795124), null=True),
        ),
    ]
