# Generated by Django 3.1.3 on 2023-11-29 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0051_auto_20231121_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 28, 23, 28, 36, 400509), null=True),
        ),
    ]
