# Generated by Django 3.1.3 on 2024-02-13 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0054_auto_20240213_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 13, 15, 31, 53, 714075), null=True),
        ),
    ]
