# Generated by Django 3.1.3 on 2024-02-19 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0055_auto_20240213_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 19, 22, 10, 22, 360781), null=True),
        ),
    ]
