# Generated by Django 3.1.3 on 2024-08-16 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0056_auto_20240219_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 16, 14, 59, 15, 161716), null=True),
        ),
    ]
