# Generated by Django 3.1.3 on 2024-08-16 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0058_auto_20240816_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 16, 23, 5, 17, 908408), null=True),
        ),
    ]
