# Generated by Django 3.1.3 on 2024-08-16 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0059_auto_20240816_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 16, 23, 7, 29, 541946), null=True),
        ),
    ]
