# Generated by Django 3.1.3 on 2025-07-01 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0060_auto_20240816_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 1, 14, 32, 50, 800594), null=True),
        ),
    ]
