# Generated by Django 3.1.3 on 2025-10-29 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0062_auto_20250701_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 29, 11, 40, 10, 615773), null=True),
        ),
    ]
