# Generated by Django 3.2.25 on 2025-12-02 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Dash', '0063_auto_20251029_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sel',
            name='Start_datetime_elli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 2, 17, 19, 56, 608879), null=True),
        ),
    ]
