# Generated by Django 3.1.3 on 2021-05-04 20:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    replaces = [('Exp_Sub', '0001_initial'), ('Exp_Sub', '0002_expbase'), ('Exp_Sub', '0003_lsp'), ('Exp_Sub', '0004_remove_expbase_name'), ('Exp_Sub', '0005_auto_20200723_1314'), ('Exp_Sub', '0006_auto_20200820_1157'), ('Exp_Sub', '0007_exppath_parent'), ('Exp_Sub', '0008_auto_20200820_1218'), ('Exp_Sub', '0009_auto_20200820_1237'), ('Exp_Sub', '0010_auto_20200820_1242'), ('Exp_Sub', '0011_auto_20200820_1631'), ('Exp_Sub', '0012_auto_20200821_1847'), ('Exp_Sub', '0013_auto_20200825_2100'), ('Exp_Sub', '0014_auto_20200826_1218'), ('Exp_Sub', '0015_auto_20200826_1300'), ('Exp_Sub', '0016_auto_20200826_2108'), ('Exp_Sub', '0017_auto_20200826_2109'), ('Exp_Sub', '0018_auto_20200827_1147'), ('Exp_Sub', '0019_auto_20200827_1817'), ('Exp_Sub', '0020_auto_20200831_1434'), ('Exp_Sub', '0021_auto_20200901_2129'), ('Exp_Sub', '0022_auto_20200901_2139'), ('Exp_Sub', '0023_auto_20200901_2147'), ('Exp_Sub', '0024_auto_20200901_2324'), ('Exp_Sub', '0025_auto_20200903_1207'), ('Exp_Sub', '0026_auto_20200903_1210'), ('Exp_Sub', '0027_auto_20200918_1347'), ('Exp_Sub', '0028_auto_20200919_1838'), ('Exp_Sub', '0029_auto_20200921_1845'), ('Exp_Sub', '0030_auto_20200921_1847'), ('Exp_Sub', '0031_auto_20200921_1848'), ('Exp_Sub', '0032_auto_20200921_1947'), ('Exp_Sub', '0033_auto_20201026_0906'), ('Exp_Sub', '0034_auto_20201026_0914'), ('Exp_Sub', '0035_auto_20201104_1900'), ('Exp_Sub', '0036_auto_20201105_1707'), ('Exp_Sub', '0037_auto_20201106_1546'), ('Exp_Sub', '0038_auto_20201106_1554'), ('Exp_Sub', '0039_auto_20201106_1618'), ('Exp_Sub', '0040_auto_20201108_1947'), ('Exp_Sub', '0041_auto_20201111_1043'), ('Exp_Sub', '0042_auto_20201111_1102'), ('Exp_Sub', '0043_auto_20201111_1113'), ('Exp_Sub', '0044_auto_20201111_1119'), ('Exp_Sub', '0045_auto_20201111_1238'), ('Exp_Sub', '0046_auto_20201111_2048'), ('Exp_Sub', '0047_auto_20201111_2054'), ('Exp_Sub', '0048_auto_20201112_1210'), ('Exp_Sub', '0049_auto_20201117_0950'), ('Exp_Sub', '0050_auto_20201120_1832'), ('Exp_Sub', '0051_auto_20201122_2222'), ('Exp_Sub', '0052_auto_20201123_1908'), ('Exp_Sub', '0053_auto_20201129_1157'), ('Exp_Sub', '0054_auto_20201129_1332'), ('Exp_Sub', '0055_auto_20201201_1302'), ('Exp_Sub', '0056_auto_20201201_2115'), ('Exp_Sub', '0057_auto_20201207_1436'), ('Exp_Sub', '0058_auto_20210211_1719'), ('Exp_Sub', '0059_auto_20210211_1947'), ('Exp_Sub', '0060_auto_20210302_2059'), ('Exp_Sub', '0061_auto_20210307_0017'), ('Exp_Sub', '0062_auto_20210307_0026'), ('Exp_Sub', '0063_auto_20210307_0032'), ('Exp_Sub', '0064_auto_20210307_1534'), ('Exp_Sub', '0065_auto_20210307_1633'), ('Exp_Sub', '0066_auto_20210308_1224'), ('Exp_Sub', '0067_auto_20210310_1727'), ('Exp_Sub', '0068_auto_20210310_1742'), ('Exp_Sub', '0069_auto_20210310_1908'), ('Exp_Sub', '0070_auto_20210311_1606'), ('Exp_Sub', '0071_auto_20210322_1601'), ('Exp_Sub', '0072_auto_20210427_1647')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_time', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Comment', models.TextField(blank=True, null=True)),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exp_Sub.exppath')),
                ('Name', models.TextField(blank=True, db_column='Name:', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LSP',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
                ('Liquid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exp_Sub.liquid')),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.CreateModel(
            name='MFL',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
                ('Gas', models.ManyToManyField(to='Exp_Sub.Gas')),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.CreateModel(
            name='ExpPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abbrev', models.CharField(max_length=3, unique=True)),
                ('Name', models.TextField(unique=True)),
                ('Path', models.TextField(unique=True)),
                ('level', models.PositiveIntegerField(default=0, editable=False)),
                ('lft', models.PositiveIntegerField(default=1, editable=False)),
                ('rght', models.PositiveIntegerField(default=2, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, default=1, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Exp_Sub.exppath')),
                ('File_ending', models.ManyToManyField(blank=True, to='Exp_Sub.FileEnding')),
            ],
        ),
        migrations.CreateModel(
            name='FileEnding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ending', models.TextField(unique=True)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('Name', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HME',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
                ('Environments', models.CharField(choices=[('1', 'Cell'), ('2', 'Room')], default='1', max_length=1)),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Born', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 27, 16, 47, 33, 260611), null=True)),
                ('Death', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 27, 16, 47, 33, 260611), null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Born', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 27, 16, 47, 33, 259605), null=True)),
                ('Death', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 27, 16, 47, 33, 259605), null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
