# Generated by Django 3.2.25 on 2026-01-20 14:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, db_column='Name:', null=True, unique=True)),
                ('Date_time', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('Comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileEnding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, null=True, unique=True)),
                ('Ending', models.TextField(unique=True)),
                ('Comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Born', models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 20, 15, 28, 7, 619039), null=True)),
                ('Death', models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 20, 15, 28, 7, 619045), null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Born', models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 20, 15, 28, 7, 618837), null=True)),
                ('Death', models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 20, 15, 28, 7, 618845), null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CAP',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Capillary', models.IntegerField(blank=True, null=True)),
                ('Link', models.TextField(blank=True, null=True)),
                ('Link_Data', models.TextField(blank=True, null=True)),
                ('FPS', models.FloatField(blank=True, null=True)),
                ('Total_Length_mm', models.FloatField(blank=True, default=50, null=True)),
                ('Width_mm', models.FloatField(blank=True, default=0.4, null=True)),
                ('Height_mm', models.FloatField(blank=True, default=0.04, null=True)),
                ('Wall_Thickness_mm', models.FloatField(blank=True, default=0.028, null=True)),
                ('Mass_g', models.FloatField(blank=True, null=True)),
                ('Effective_Length_mm', models.FloatField(blank=True, null=True)),
                ('Glass_Plate', models.BooleanField(blank=True, null=True)),
                ('Fixture_Mass_without_Glass_Plate_g', models.FloatField(blank=True, null=True)),
                ('Fixture_Mass_with_Glass_Plate_g', models.FloatField(blank=True, null=True)),
                ('Eigenfrequency_Hz', models.FloatField(blank=True, null=True)),
                ('Spring_Constant_N_per_m', models.FloatField(blank=True, null=True)),
                ('Delta_Spring_Constant_N_per_m', models.FloatField(blank=True, null=True)),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.CreateModel(
            name='HIA',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
                ('Environments', models.CharField(choices=[('1', 'Cell'), ('2', 'Room')], default='1', max_length=1)),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.CreateModel(
            name='HME',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
                ('Environments', models.CharField(choices=[('1', 'Cell'), ('2', 'Room')], default='1', max_length=1)),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.CreateModel(
            name='TCM',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.CreateModel(
            name='ExpPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abbrev', models.CharField(max_length=3, unique=True)),
                ('Name', models.TextField(unique=True)),
                ('Path', models.TextField(unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('File_ending', models.ManyToManyField(blank=True, to='Exp_Sub.FileEnding')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Exp_Sub.exppath')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expbase',
            name='Device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exp_Sub.exppath'),
        ),
        migrations.CreateModel(
            name='MFR',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
                ('Gas', models.ManyToManyField(to='Exp_Sub.Gas')),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.CreateModel(
            name='MFL',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
                ('Gas', models.ManyToManyField(to='Exp_Sub.Gas')),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.CreateModel(
            name='LSP',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
                ('Liquid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exp_Sub.liquid')),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.CreateModel(
            name='HBK',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('px_to_mm', models.FloatField(blank=True, null=True)),
                ('Link', models.TextField(blank=True, null=True)),
                ('Link_Data', models.TextField(blank=True, null=True)),
                ('Liquid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exp_Sub.liquid')),
            ],
            bases=('Exp_Sub.expbase',),
        ),
    ]
