# Generated by Django 3.1.3 on 2022-08-10 11:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Sub', '0020_auto_20220614_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIA',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
                ('Environments', models.CharField(choices=[('1', 'Cell'), ('2', 'Room')], default='1', max_length=1)),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.AlterField(
            model_name='gas',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 10, 13, 26, 22, 792355), null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 10, 13, 26, 22, 792373), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 10, 13, 26, 22, 791602), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 10, 13, 26, 22, 791625), null=True),
        ),
    ]
