# Generated by Django 3.1.3 on 2022-08-21 12:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Sub', '0022_auto_20220816_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCM',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Link', models.TextField(blank=True, null=True)),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.AlterField(
            model_name='gas',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 21, 14, 28, 59, 345041), null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 21, 14, 28, 59, 345049), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 21, 14, 28, 59, 344733), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 21, 14, 28, 59, 344743), null=True),
        ),
    ]
