# Generated by Django 3.1.3 on 2022-11-02 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_Sub', '0028_auto_20221029_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAP',
            fields=[
                ('expbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exp_Sub.expbase')),
                ('Capillary', models.IntegerField(blank=True, null=True)),
                ('Link', models.TextField(blank=True, null=True)),
                ('Link_Data', models.TextField(blank=True, null=True)),
                ('FPS', models.FloatField(blank=True, null=True)),
                ('Total_Length_mm', models.FloatField(blank=True, default=50, null=True)),
                ('Width_mm', models.FloatField(blank=True, default=0.4, null=True)),
                ('Height_mm', models.FloatField(blank=True, default=0.04, null=True)),
                ('Wall_Thickness_mm', models.FloatField(blank=True, default=0.028, null=True)),
                ('Mass_g', models.FloatField(blank=True, null=True)),
                ('Effective_Length_mm', models.FloatField(blank=True, null=True)),
                ('Glass_Plate', models.BooleanField(blank=True, null=True)),
                ('Fixture_Mass_without_Glass_Plate_g', models.FloatField(blank=True, null=True)),
                ('Fixture_Mass_with_Glass_Plate_g', models.FloatField(blank=True, null=True)),
                ('Eigenfrequency_Hz', models.FloatField(blank=True, null=True)),
                ('Spring_Constant_N_per_m', models.FloatField(blank=True, null=True)),
                ('Delta_Spring_Constant_N_per_m', models.FloatField(blank=True, null=True)),
            ],
            bases=('Exp_Sub.expbase',),
        ),
        migrations.AlterField(
            model_name='gas',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 11, 54, 45, 97192), null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 11, 54, 45, 97210), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Born',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 11, 54, 45, 96400), null=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='Death',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 11, 54, 45, 96428), null=True),
        ),
    ]
